# Generated by Django 5.2.7 on 2025-10-27 00:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documentpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_preview_directory_path),
        ),
    ]
