# Generated by Django 5.2.7 on 2025-10-28 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_extracted_content_document_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_translation_api',
            field=models.CharField(default='google_translate', help_text='API de traducción preferida', max_length=50),
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(help_text="Idioma de origen (ej: 'es')", max_length=10)),
                ('target_language', models.CharField(help_text="Idioma de destino (ej: 'en')", max_length=10)),
                ('translated_content', models.TextField(blank=True, help_text='Contenido del documento traducido.')),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-translated_at'],
            },
        ),
    ]
