# Generated by Django 5.2.8 on 2025-11-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_preferred_translation_api_translationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
