# Generated by Django 5.2.8 on 2025-11-19 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_ai_requests_count',
            field=models.IntegerField(default=0, help_text='Peticiones a la IA hoy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_messages_count',
            field=models.IntegerField(default=0, help_text='Mensajes enviados hoy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ai_request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_message_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
